# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: temperaturas.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'temperaturas.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12temperaturas.proto\"\x1e\n\x0c\x43odigoCiudad\x12\x0e\n\x06\x63odigo\x18\x01 \x01(\t\"/\n\x0bTemperatura\x12\r\n\x05valor\x18\x01 \x01(\x01\x12\x11\n\ttimestamp\x18\x02 \x01(\x03\";\n\x15RespuestaTemperaturas\x12\"\n\x0ctemperaturas\x18\x01 \x03(\x0b\x32\x0c.Temperatura2[\n\x14ServicioTemperaturas\x12\x43\n\x1aObtenerUltimasTemperaturas\x12\r.CodigoCiudad\x1a\x16.RespuestaTemperaturasb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'temperaturas_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODIGOCIUDAD']._serialized_start=22
  _globals['_CODIGOCIUDAD']._serialized_end=52
  _globals['_TEMPERATURA']._serialized_start=54
  _globals['_TEMPERATURA']._serialized_end=101
  _globals['_RESPUESTATEMPERATURAS']._serialized_start=103
  _globals['_RESPUESTATEMPERATURAS']._serialized_end=162
  _globals['_SERVICIOTEMPERATURAS']._serialized_start=164
  _globals['_SERVICIOTEMPERATURAS']._serialized_end=255
# @@protoc_insertion_point(module_scope)
